# Site settings
title: "Jieun Seong's Webpage"
description: "title: Jieun Seong's Webpage"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jieun Seong"
resume_title:                   "Intergrated Ph.D. Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jieun3891@snu.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hi there! I'm a <strong><u>integrated Ph.D. student</u></strong> in <strong><u>Nursing Informatics at Seoul National University College of Nursing</u></strong>. With a background in the Neonatal Intensive Care Unit (NICU), I’m passionate about bridging clinical nursing with data, technology, and AI to improve healthcare practice. I’m currently working full-time as a researcher at the <strong><u>Human-Centered Artificial Intelligence Lab (HCAIL)</u></strong>. This blog is a space where I share insights on nursing informatics, clinical experiences, and my journey as a researcher. I hope to connect with others who are interested in the future of nursing and healthcare innovation. Thanks for visiting!</p>"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://jieunseong28.github.io/"
  resume_twitter_url:           "https://x.com/jieunseong_"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "www.linkedin.com/in/jieunseong"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  resume_resume_url:            "resume.pdf"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
